name: 'Prepare Release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Module version to be released.'
        required: false
        default: ''
        type: string
      base-branch:
        description: 'The branch that will be used as the origin for the release branch.'
        required: false
        default: ''
        type: string

jobs:
  prepare_release:
    uses: smortex/shared-actions/.github/workflows/prepare_release.yml@prepare-release
    with:
      version: ${{ github.event.inputs.version }}
      allowed_owner: 'smortex'
    secrets:
      github_pat: ${{ secrets.GHA_TOKEN }}
