name: 'Release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Module version to be released.'
        required: false
        default: ''
        type: string
      base-branch:
        description: 'The branch where we do this release.'
        required: false
        default: ''
        type: string

permissions: {}

jobs:
  release:
    uses: smortex/shared-actions/.github/workflows/release.yml@relase-rc
    with:
      allowed_owner: 'OpenVoxProject'
      base-branch: ${{ github.event.inputs.base-branch }}
      version: ${{ github.event.inputs.version }}
    secrets:
      github_pat: ${{ secrets.OPENVOXBOT_COMMIT_AND_PRS }}
      ssh_private_key: ${{ secrets.OPENVOXBOT_SSH_PRIVATE_KEY }}
