---
name: A tag is pushed v2

on:
  push:
    tags:
      - '*'

jobs:
  document:
    name: Document what happen when a tag is pushed v2
    runs-on: ubuntu-24.04
    # Optional but recommended to use a specific environment
    environment: release

    steps:
      - name: Tell us about this tagv2
        run: echo "TAGv2 ${{ github.ref_name }}"
      - name: Show the environment
        run: env
